config = {
    "data_root": "/mnt/data1/rove/asset/GF7_Building/3Bands",
    "batch_size": 12,
    "num_workers": 4,
    "image_size": 512,
    "input_channels": 3,
    "use_nir": False,
    "encoder_pretrained": True,
    "shape_loss_weight": 0.4,
    "dice_ratio": 0.5,
    "num_epochs": 400,
    "learning_rate": 5e-4,
    "weight_decay": 1e-3,
    "warmup_epochs": 10,
    "min_lr": 1e-6,
    "save_dir": "./runs",
    "model_name": "STDSNet",
    "num_classes": 2,
    "seed": 3047,
}
