_wandb:
    value:
        cli_version: 0.22.1
        e:
            g29ymm4o8i26al9kazl8g2gkoiu7t6it:
                codePath: train/train_transccV2.py
                codePathLocal: train/train_transccV2.py
                cpu_count: 24
                cpu_count_logical: 24
                cudaVersion: "13.0"
                disk:
                    /:
                        total: "1967317549056"
                        used: "147240464384"
                email: songch5910@gmail.com
                executable: /home/rove/BuindingsSeg/.venv/bin/python
                git:
                    commit: 015a741f6dfc95ff92c91292aa926a89a424f883
                    remote: git@github.com:Song-Aug/RsSegmentation.git
                gpu: NVIDIA GeForce RTX 5090
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Blackwell
                      cudaCores: 21760
                      memoryTotal: "34190917632"
                      name: NVIDIA GeForce RTX 5090
                      uuid: GPU-78b80b7e-b2e1-acea-0c6e-d0e56c29a6fc
                host: pc-System-Product-Name
                memory:
                    total: "134378942464"
                os: Linux-6.8.0-83-generic-x86_64-with-glibc2.35
                program: /home/rove/BuindingsSeg/train/train_transccV2.py
                python: CPython 3.10.12
                root: /home/rove/BuindingsSeg
                startedAt: "2025-10-02T00:46:31.464058Z"
                writerId: g29ymm4o8i26al9kazl8g2gkoiu7t6it
        m: []
        python_version: 3.10.12
        t:
            "1":
                - 1
                - 41
                - 49
                - 63
            "2":
                - 1
                - 41
                - 49
                - 63
            "3":
                - 1
                - 2
                - 13
                - 15
                - 16
            "4": 3.10.12
            "5": 0.22.1
            "12": 0.22.1
            "13": linux-x86_64
batch_size:
    value: 12
data_root:
    value: /mnt/data1/rove/asset/GF7_Building/3Bands
fusion_strategy:
    value: interpolate
image_size:
    value: 512
input_channels:
    value: 3
learning_rate:
    value: 0.001
min_lr:
    value: 1e-06
model_input_channels:
    value: 3
model_name:
    value: TransCC_V2
model_total_params:
    value: 57756842
model_trainable_params:
    value: 57756842
num_classes:
    value: 2
num_epochs:
    value: 300
num_workers:
    value: 4
pretrained_weights:
    value: ./pretrained_weights/vit_base_patch16_224.pth
save_dir:
    value: ./runs
seed:
    value: 42
use_nir:
    value: false
warmup_epochs:
    value: 5
weight_decay:
    value: 0.0001
